# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce3f93b6a1641c78722a7b8e4ac9d9cdbaa962070bf424fbf441e59f570a918c5b72ba3468600d8fac99635280b9188f66a05d7136d9ac3c42a646b0786aeb6

test:
  secret_key_base: 8ead240622c147358cc28995df82aa4a2ea4ccfe3a5ce6cde3bf38ef16cd616933a7893907259701837dc03f512278312bd4413fac26d36fe112dd90765dda42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
